# Pandas Exercises — Titanic Dataset

Practise the core pandas skills on a real-world, **messy** dataset: the famous Titanic passenger list.

Unlike a clean dataset, this one has **missing values** (`Age`, `Cabin`, `Embarked`), a mix of **categorical and numeric** columns, and plenty to explore — perfect for practising cleaning, selecting, and aggregating.

**The columns:**

| Column | Meaning |
|---|---|
| `Survived` | 0 = died, 1 = survived |
| `Pclass` | Ticket class (1 = 1st, 2 = 2nd, 3 = 3rd) |
| `Name` | Passenger name |
| `Sex` | male / female |
| `Age` | Age in years (has missing values) |
| `SibSp` | # of siblings / spouses aboard |
| `Parch` | # of parents / children aboard |
| `Ticket` | Ticket number |
| `Fare` | Ticket price |
| `Cabin` | Cabin number (mostly missing) |
| `Embarked` | Port of embarkation (C, Q, S) |

**Instructions:** Solve each exercise in the empty cell below its prompt. The full solutions will be share after you're done; try every exercise yourself first before checking.

## 1. Loading and Exploring the Data

**Exercise 1.** Import pandas (as `pd`) and read `../data/titanic.csv` into a DataFrame called `df`. Display the first 5 rows.

In [124]:
# Your code here
import pandas as pd
df=pd.read_csv(r"C:\Users\HP\Downloads\titanic.csv")
df=df.drop(columns="PassengerId")
df.head()

,Name,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
0,"Braund, Mr. Owen Harris",3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,"Heikkinen, Miss. Laina",3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,1,0,113803,53.1000,C123,S,1
4,"Allen, Mr. William Henry",3,male,35.0,0,0,373450,8.0500,NaN,S,0

**Exercise 2.** How many rows and columns does the dataset have? Use the attribute that returns this as a tuple.

In [125]:
# Your code here
df.shape
#891 rows and 11 columns

(891, 11)

**Exercise 3.** Use a single method to print column names, non-null counts, and data types. Which columns have missing values?

In [126]:
# Your code here
df.columns,df.dtypes,df.isna().sum()

(Index(['Name', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare',
        'Cabin', 'Embarked', 'Survived'],
       dtype='str'),
 Name            str
 Pclass        int64
 Sex             str
 Age         float64
 SibSp         int64
 Parch         int64
 Ticket          str
 Fare        float64
 Cabin           str
 Embarked        str
 Survived      int64
 dtype: object,
 Name          0
 Pclass        0
 Sex           0
 Age         177
 SibSp         0
 Parch         0
 Ticket        0
 Fare          0
 Cabin       687
 Embarked      2
 Survived      0
 dtype: int64)

**Exercise 4.** Show the summary statistics (count, mean, std, min, quartiles, max) for the numeric columns.

In [127]:
# Your code here
df.describe()

           Pclass         Age       SibSp       Parch        Fare    Survived
count  891.000000  714.000000  891.000000  891.000000  891.000000  891.000000
mean     2.308642   29.699118    0.523008    0.381594   32.204208    0.383838
std      0.836071   14.526497    1.102743    0.806057   49.693429    0.486592
min      1.000000    0.420000    0.000000    0.000000    0.000000    0.000000
25%      2.000000   20.125000    0.000000    0.000000    7.910400    0.000000
50%      3.000000   28.000000    0.000000    0.000000   14.454200    0.000000
75%      3.000000   38.000000    1.000000    0.000000   31.000000    1.000000
max      3.000000   80.000000    8.000000    6.000000  512.329200    1.000000

## 2. Selecting and Filtering Data

**Exercise 5.** Select just the `Name` and `Age` columns and show the first 10 rows.

In [128]:
# Your code here
df1=df[["Name","Age"]]
df1.head(10)

                                                Name   Age
0                            Braund, Mr. Owen Harris  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                             Heikkinen, Miss. Laina  26.0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                           Allen, Mr. William Henry  35.0
5                                   Moran, Mr. James   NaN
6                            McCarthy, Mr. Timothy J  54.0
7                     Palsson, Master. Gosta Leonard   2.0
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  27.0
9                Nasser, Mrs. Nicholas (Adele Achem)  14.0

**Exercise 6.** Use boolean filtering to keep only the passengers who **survived** (`Survived == 1`). How many were there?

In [133]:
# Your code here
survived = df[df["Survived"] == 1]
survived

,Name,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,"Heikkinen, Miss. Laina",3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,1,0,113803,53.1000,C123,S,1
8,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",3,female,27.0,0,2,347742,11.1333,NaN,S,1
9,"Nasser, Mrs. Nicholas (Adele Achem)",2,female,14.0,1,0,237736,30.0708,NaN,C,1
...,...,...,...,...,...,...,...,...,...,...,...
875,"Najib, Miss. Adele Kiamie ""Jane""",3,female,15.0,0,0,2667,7.2250,NaN,C,1
879,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",1,female,56.0,0,1,11767,83.1583,C50,C,1
880,"Shelley, Mrs. William (Imanita Parrish Hall)",2,female,25.0,0,1,230433,26.0000,NaN,S,1
887,"Graham, Miss. Margaret Edith",1,female,19.0,0,0,112053,30.0000,B42,S,1
889,"Behr, Mr. Karl Howell",1,male,26.0,0,0,111369,30.0000,C148,C,1

**Exercise 7.** Filter for passengers who were in **1st class** (`Pclass == 1`) **AND** were **female**. (Combine two conditions with `&`, wrapping each in parentheses.)

In [134]:
# Your code here
df3=df[(df["Pclass"]==1) & (df["Sex"]=="female")]
df3

,Name,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Survived
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,1,0,PC 17599,71.2833,C85,C,1
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,1,0,113803,53.1000,C123,S,1
11,"Bonnell, Miss. Elizabeth",1,female,58.0,0,0,113783,26.5500,C103,S,1
31,"Spencer, Mrs. William Augustus (Marie Eugenie)",1,female,NaN,1,0,PC 17569,146.5208,B78,C,1
52,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",1,female,49.0,1,0,PC 17572,76.7292,D33,C,1
...,...,...,...,...,...,...,...,...,...,...,...
856,"Wick, Mrs. George Dennick (Mary Hitchcock)",1,female,45.0,1,1,36928,164.8667,NaN,S,1
862,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",1,female,48.0,0,0,17466,25.9292,D17,S,1
871,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",1,female,47.0,1,1,11751,52.5542,D35,S,1
879,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",1,female,56.0,0,1,11767,83.1583,C50,C,1
887,"Graham, Miss. Margaret Edith",1,female,19.0,0,0,112053,30.0000,B42,S,1

**Exercise 8.** Use `.loc` to select the rows at index 0, 1 and 2, but only the `Name`, `Sex` and `Survived` columns.

In [135]:
# Your code here
top_rows = df.loc[0:2, ["Name", "Sex", "Survived"]]

## 3. Handling Missing Data

**Exercise 9.** Count the number of missing values in **each** column. (Hint: combine `.isnull()` with `.sum()`.)

In [136]:
# Your code here
df.isnull().sum()

Name          0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Ticket        0
Fare          0
Cabin       687
Embarked      2
Survived      0
dtype: int64

**Exercise 10.** Fill the missing `Age` values with the **median** age, and assign the result back to the `Age` column. Then confirm there are no missing ages left.

In [137]:
# Your code here
df["Age"]=df["Age"].fillna(df["Age"].median())
df["Age"].isnull().sum()

np.int64(0)

**Exercise 11.** The `Embarked` column has only 2 missing values. Fill them with the **most common** port (the mode). The `Cabin` column is mostly empty — **drop** that whole column instead.

*Tip: `df["Embarked"].mode()` returns a Series; take the first element with `[0]`. Use `df.drop(columns=...)` to remove a column.*

In [162]:
# Your code here
df["Embarked"]=df["Embarked"].fillna(df["Embarked"].mode()[0])
df=df.drop(columns=["Cabin"])
df.columns

Index(['Name', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare',
       'Embarked', 'Survived', 'FamilySize', 'IsAlone', 'AgeGroup'],
      dtype='str')

## 4. Grouping and Aggregating

**Exercise 12.** What was the overall **survival rate**? (Because `Survived` is 0/1, its mean equals the proportion who survived.)

In [163]:
# Your code here
survival_rate=df["Survived"].mean()
survival_rate

np.float64(0.3838383838383838)

**Exercise 13.** Group by `Sex` and find the survival rate for each. Did men or women survive at a higher rate?

In [164]:
# Your code here
female_survival_rate=df[df["Sex"]=="female"]["Survived"].mean()*100
male_survival_rate=df[df["Sex"]=="male"]["Survived"].mean()*100
female_survival_rate,male_survival_rate

(np.float64(74.20382165605095), np.float64(18.890814558058924))

**Exercise 14.** Group by `Pclass` and find the survival rate for each class. Then group by **both** `Pclass` and `Sex` together.

In [165]:
# Your code here
pclass_1_rate=df[df["Pclass"]==1]["Survived"].mean()*100
pclass_2_rate=df[df["Pclass"]==2]["Survived"].mean()*100
pclass_3_rate=df[df["Pclass"]==3]["Survived"].mean()*100
df.groupby(["Pclass","Sex"]),pclass_1_rate,pclass_2_rate,pclass_3_rate

(<pandas.api.typing.DataFrameGroupBy object at 0x00000218614BC560>,
 np.float64(62.96296296296296),
 np.float64(47.28260869565217),
 np.float64(24.236252545824847))

**Exercise 15.** Use `pd.crosstab()` to build a frequency table counting how many passengers of each `Sex` fall into each `Survived` value (0 or 1).

In [166]:
# Your code here
dfff=pd.crosstab(df["Sex"],df["Survived"])
dfff

Survived    0    1
Sex
female     81  233
male      468  109

## 5. Creating and Transforming Columns

**Exercise 16.** Create a new column `FamilySize` equal to `SibSp + Parch + 1` (the +1 counts the passenger themselves).

In [167]:
# Your code here
df["FamilySize"]=df["SibSp"]+df["Parch"]+1
df

,Name,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Survived,FamilySize,IsAlone,AgeGroup
0,"Braund, Mr. Owen Harris",3,male,22.0,1,0,A/5 21171,7.2500,S,0,2,0,Adult
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,1,0,PC 17599,71.2833,C,1,2,0,Adult
2,"Heikkinen, Miss. Laina",3,female,26.0,0,0,STON/O2. 3101282,7.9250,S,1,1,1,Adult
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,1,0,113803,53.1000,S,1,2,0,Adult
4,"Allen, Mr. William Henry",3,male,35.0,0,0,373450,8.0500,S,0,1,1,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,"Montvila, Rev. Juozas",2,male,27.0,0,0,211536,13.0000,S,0,1,1,Adult
887,"Graham, Miss. Margaret Edith",1,female,19.0,0,0,112053,30.0000,S,1,1,1,Adult
888,"Johnston, Miss. Catherine Helen ""Carrie""",3,female,28.0,1,2,W./C. 6607,23.4500,S,0,4,0,Adult
889,"Behr, Mr. Karl Howell",1,male,26.0,0,0,111369,30.0000,C,1,1,1,Adult
890,"Dooley, Mr. Patrick",3,male,32.0,0,0,370376,7.7500,Q,0,1,1,Adult

**Exercise 17.** Create a new column `IsAlone` that is `1` when `FamilySize == 1` and `0` otherwise.

*Tip: a boolean comparison gives True/False — convert it to integers with `.astype(int)`.*

In [168]:
# Your code here
df["IsAlone"] = 0
df["IsAlone"] = (df["SibSp"] + df["Parch"] + 1 == 1).astype(int)
df.head()

,Name,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Survived,FamilySize,IsAlone,AgeGroup
0,"Braund, Mr. Owen Harris",3,male,22.0,1,0,A/5 21171,7.2500,S,0,2,0,Adult
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,female,38.0,1,0,PC 17599,71.2833,C,1,2,0,Adult
2,"Heikkinen, Miss. Laina",3,female,26.0,0,0,STON/O2. 3101282,7.9250,S,1,1,1,Adult
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,female,35.0,1,0,113803,53.1000,S,1,2,0,Adult
4,"Allen, Mr. William Henry",3,male,35.0,0,0,373450,8.0500,S,0,1,1,Adult

**Exercise 18.** Use `.apply()` with a custom function (or a `lambda`) to create an `AgeGroup` column that labels each passenger as `"Child"` if `Age < 18`, otherwise `"Adult"`.

In [169]:
# Your code here
df["AgeGroup"] = df["Age"].apply(lambda x: "Child" if x < 18 else "Adult")
df["AgeGroup"].unique()

<StringArray>
['Adult', 'Child']
Length: 2, dtype: str

**Exercise 19.** Using your new `AgeGroup` column, what was the survival rate for children vs adults? (Group by `AgeGroup` and take the mean of `Survived`.)

In [170]:
# Your code here
df.groupby(["AgeGroup"])["Survived"].mean()*100

AgeGroup
Adult    36.118252
Child    53.982301
Name: Survived, dtype: float64

## 6. Sorting and Exporting

**Exercise 20.** Sort the DataFrame by `Fare` from highest to lowest and show the top 5 paying passengers (`Name`, `Pclass`, `Fare`).

In [171]:
# Your code here
top_5 = df.sort_values("Fare", ascending=False)[["Name", "Pclass", "Fare"]].head(5)

**Exercise 21.** Save your cleaned and enriched DataFrame to `../data/titanic-cleaned.csv` *without* the extra index column.

*Tip: pass `index=False` to `.to_csv()`.*

In [173]:
# Your code here
df.to_csv("titanic-cleaned.csv",index=False)

## 🏆 Challenge Exercises

Combine what you've learned:

1. What was the **average fare** paid by passengers in each `Pclass`?
2. Among passengers travelling **alone** (`IsAlone == 1`), what was the survival rate compared to those with family?
3. Find the **oldest** and **youngest** passenger who survived.
4. Build a crosstab of `Pclass` vs `Survived`, then add `normalize='index'` to turn the counts into per-class proportions.

In [ ]:
# Your challenge code here