In [1]:
import pandas as pd
print(pd.__version__)

3.0.5

Datatypes

In [3]:
#series is a 1-dimensional column of data
cars=pd.Series(["bmw","toyota","mercedes"])
cars

0         bmw
1      toyota
2    mercedes
dtype: str

In [4]:
colors=pd.Series(["blue","red","pink"])
colors

0    blue
1     red
2    pink
dtype: str

In [5]:
#a dataframe is 2-dimensional: columns and rows
df=pd.DataFrame({
"car_type":cars,
"colors":colors
}) 
df

   car_type colors
0       bmw   blue
1    toyota    red
2  mercedes   pink

In [6]:
cars_sales=pd.read_csv(r'C:\Users\HP\Downloads\cars_sales.csv')
cars_sales

               name   color  odometer(km)  doors  price
0    Toyota Corolla   White        120000      4  15000
1       Honda Civic   Black         95000      4  18000
2      Ford Mustang     Red         60000      2  35000
3            BMW X5    Blue         80000      4  45000
4  Mercedes C-Class  Silver         70000      4  40000
5   Hyundai Elantra    Grey        110000      4  14000
6      Kia Sportage   White         90000      4  22000
7     Nissan Altima   Black        100000      4  16000
8   Volkswagen Golf    Blue         85000      4  19000
9           Audi A4     Red         75000      4  38000

In [7]:
cars_sales.dtypes

name              str
color             str
odometer(km)    int64
doors           int64
price           int64
dtype: object

In [9]:
cars_sales.describe()

        odometer(km)      doors         price
count      10.000000  10.000000     10.000000
mean    88500.000000   3.800000  26200.000000
std     18416.478129   0.632456  11905.180945
min     60000.000000   2.000000  14000.000000
25%     76250.000000   4.000000  16500.000000
50%     87500.000000   4.000000  20500.000000
75%     98750.000000   4.000000  37250.000000
max    120000.000000   4.000000  45000.000000

In [10]:
cars_sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          10 non-null     str
 1   color         10 non-null     str
 2   odometer(km)  10 non-null     int64
 3   doors         10 non-null     int64
 4   price         10 non-null     int64
dtypes: int64(3), str(2)
memory usage: 532.0 bytes

In [11]:
cars_sales.mean(numeric_only=True)

odometer(km)    88500.0
doors               3.8
price           26200.0
dtype: float64

In [13]:
cars_prices=pd.Series([10000,3000,27000])
cars_prices.mean

<bound method Series.mean of 0    10000
1     3000
2    27000
dtype: int64>

View and select data

In [14]:
cars_sales.head()

               name   color  odometer(km)  doors  price
0    Toyota Corolla   White        120000      4  15000
1       Honda Civic   Black         95000      4  18000
2      Ford Mustang     Red         60000      2  35000
3            BMW X5    Blue         80000      4  45000
4  Mercedes C-Class  Silver         70000      4  40000

In [15]:
cars_sales.tail()

              name  color  odometer(km)  doors  price
5  Hyundai Elantra   Grey        110000      4  14000
6     Kia Sportage  White         90000      4  22000
7    Nissan Altima  Black        100000      4  16000
8  Volkswagen Golf   Blue         85000      4  19000
9          Audi A4    Red         75000      4  38000

In [19]:
cars_sales.loc[3]

name            BMW X5
color             Blue
odometer(km)     80000
doors                4
price            45000
Name: 3, dtype: object

In [21]:
cars_sales.iloc[6]

name            Kia Sportage
color                  White
odometer(km)           90000
doors                      4
price                  22000
Name: 6, dtype: object

In [22]:
cars_sales["color"]

0     White
1     Black
2       Red
3      Blue
4    Silver
5      Grey
6     White
7     Black
8      Blue
9       Red
Name: color, dtype: str

In [26]:
cars_sales[cars_sales["odometer(km)"]>100000]

              name  color  odometer(km)  doors  price
0   Toyota Corolla  White        120000      4  15000
5  Hyundai Elantra   Grey        110000      4  14000

In [28]:
cars_sales[cars_sales["name"]=="Toyota Corolla"]

             name  color  odometer(km)  doors  price
0  Toyota Corolla  White        120000      4  15000

In [29]:
pd.crosstab(cars_sales["name"],cars_sales["doors"])

doors             2  4
name
Audi A4           0  1
BMW X5            0  1
Ford Mustang      1  0
Honda Civic       0  1
Hyundai Elantra   0  1
Kia Sportage      0  1
Mercedes C-Class  0  1
Nissan Altima     0  1
Toyota Corolla    0  1
Volkswagen Golf   0  1

In [33]:
cars_sales.groupby(["doors"]).mean(numeric_only=True)

       odometer(km)         price
doors
2      60000.000000  35000.000000
4      91666.666667  25222.222222

In [36]:
cars_sales["name"]=cars_sales["name"].str.lower()

In [37]:
cars_sales

               name   color  odometer(km)  doors  price
0    toyota corolla   White        120000      4  15000
1       honda civic   Black         95000      4  18000
2      ford mustang     Red         60000      2  35000
3            bmw x5    Blue         80000      4  45000
4  mercedes c-class  Silver         70000      4  40000
5   hyundai elantra    Grey        110000      4  14000
6      kia sportage   White         90000      4  22000
7     nissan altima   Black        100000      4  16000
8   volkswagen golf    Blue         85000      4  19000
9           audi a4     Red         75000      4  38000

In [60]:
cars_missing_df=pd.read_csv(r'C:\Users\HP\Downloads\car-sales-missing-data.csv')
cars_missing_df

     Make Colour  Odometer  Doors    Price
0  Toyota  White  150043.0    4.0   $4,000
1   Honda    Red   87899.0    4.0   $5,000
2  Toyota   Blue       NaN    3.0   $7,000
3     BMW  Black   11179.0    5.0  $22,000
4  Nissan  White  213095.0    4.0   $3,500
5  Toyota  Green       NaN    4.0   $4,500
6   Honda    NaN       NaN    4.0   $7,500
7   Honda   Blue       NaN    4.0      NaN
8  Toyota  White   60000.0    NaN      NaN
9     NaN  White   31600.0    4.0   $9,700

In [61]:
cars_missing_df["Odometer"]=cars_missing_df["Odometer"].fillna(cars_missing_df["Odometer"].mean(),inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_8524\983036004.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  cars_missing_df["Odometer"]=cars_missing_df["Odometer"].fillna(cars_missing_df["Odometer"].mean(),inplace=True)

In [62]:
cars_missing_df

     Make Colour       Odometer  Doors    Price
0  Toyota  White  150043.000000    4.0   $4,000
1   Honda    Red   87899.000000    4.0   $5,000
2  Toyota   Blue   92302.666667    3.0   $7,000
3     BMW  Black   11179.000000    5.0  $22,000
4  Nissan  White  213095.000000    4.0   $3,500
5  Toyota  Green   92302.666667    4.0   $4,500
6   Honda    NaN   92302.666667    4.0   $7,500
7   Honda   Blue   92302.666667    4.0      NaN
8  Toyota  White   60000.000000    NaN      NaN
9     NaN  White   31600.000000    4.0   $9,700

In [65]:
cars_missing_df.dropna(inplace=True)

In [66]:
cars_missing_df

     Make Colour       Odometer  Doors    Price
0  Toyota  White  150043.000000    4.0   $4,000
1   Honda    Red   87899.000000    4.0   $5,000
2  Toyota   Blue   92302.666667    3.0   $7,000
3     BMW  Black   11179.000000    5.0  $22,000
4  Nissan  White  213095.000000    4.0   $3,500
5  Toyota  Green   92302.666667    4.0   $4,500

In [68]:
seats_column=pd.Series([5,5,5,5,5,5])
cars_missing_df["Seats"]=seats_column
cars_missing_df

     Make Colour       Odometer  Doors    Price  Seats
0  Toyota  White  150043.000000    4.0   $4,000      5
1   Honda    Red   87899.000000    4.0   $5,000      5
2  Toyota   Blue   92302.666667    3.0   $7,000      5
3     BMW  Black   11179.000000    5.0  $22,000      5
4  Nissan  White  213095.000000    4.0   $3,500      5
5  Toyota  Green   92302.666667    4.0   $4,500      5

In [69]:
engine_size=[1.3,2.4,3.6,4.8,5.2,2.8]
cars_missing_df["Engine Size"]=engine_size
cars_missing_df

     Make Colour       Odometer  Doors    Price  Seats  Engine Size
0  Toyota  White  150043.000000    4.0   $4,000      5          1.3
1   Honda    Red   87899.000000    4.0   $5,000      5          2.4
2  Toyota   Blue   92302.666667    3.0   $7,000      5          3.6
3     BMW  Black   11179.000000    5.0  $22,000      5          4.8
4  Nissan  White  213095.000000    4.0   $3,500      5          5.2
5  Toyota  Green   92302.666667    4.0   $4,500      5          2.8

In [72]:
cars_sales["price per km"]=cars_sales["price"]/cars_sales["odometer(km)"]

In [73]:
cars_sales

               name   color  odometer(km)  doors  price  price per km
0    toyota corolla   White        120000      4  15000      0.125000
1       honda civic   Black         95000      4  18000      0.189474
2      ford mustang     Red         60000      2  35000      0.583333
3            bmw x5    Blue         80000      4  45000      0.562500
4  mercedes c-class  Silver         70000      4  40000      0.571429
5   hyundai elantra    Grey        110000      4  14000      0.127273
6      kia sportage   White         90000      4  22000      0.244444
7     nissan altima   Black        100000      4  16000      0.160000
8   volkswagen golf    Blue         85000      4  19000      0.223529
9           audi a4     Red         75000      4  38000      0.506667

In [74]:
cars_sales["number of wheels"]=4
cars_sales

,name,color,odometer(km),doors,price,price per km,number of wheels
0,toyota corolla,White,120000,4,15000,0.125000,4
1,honda civic,Black,95000,4,18000,0.189474,4
2,ford mustang,Red,60000,2,35000,0.583333,4
3,bmw x5,Blue,80000,4,45000,0.562500,4
4,mercedes c-class,Silver,70000,4,40000,0.571429,4
5,hyundai elantra,Grey,110000,4,14000,0.127273,4
6,kia sportage,White,90000,4,22000,0.244444,4
7,nissan altima,Black,100000,4,16000,0.160000,4
8,volkswagen golf,Blue,85000,4,19000,0.223529,4
9,audi a4,Red,75000,4,38000,0.506667,4

In [75]:
cars_sales=cars_sales.drop(["price per km"],axis=1)
cars_sales

               name   color  odometer(km)  doors  price  number of wheels
0    toyota corolla   White        120000      4  15000                 4
1       honda civic   Black         95000      4  18000                 4
2      ford mustang     Red         60000      2  35000                 4
3            bmw x5    Blue         80000      4  45000                 4
4  mercedes c-class  Silver         70000      4  40000                 4
5   hyundai elantra    Grey        110000      4  14000                 4
6      kia sportage   White         90000      4  22000                 4
7     nissan altima   Black        100000      4  16000                 4
8   volkswagen golf    Blue         85000      4  19000                 4
9           audi a4     Red         75000      4  38000                 4

In [77]:
cars_sales_sample=cars_sales.sample(frac=0.5)
cars_sales_sample

               name   color  odometer(km)  doors  price  number of wheels
4  mercedes c-class  Silver         70000      4  40000                 4
7     nissan altima   Black        100000      4  16000                 4
5   hyundai elantra    Grey        110000      4  14000                 4
1       honda civic   Black         95000      4  18000                 4
3            bmw x5    Blue         80000      4  45000                 4

In [78]:
cars_sales_sample.reset_index()
cars_sales_sample

               name   color  odometer(km)  doors  price  number of wheels
4  mercedes c-class  Silver         70000      4  40000                 4
7     nissan altima   Black        100000      4  16000                 4
5   hyundai elantra    Grey        110000      4  14000                 4
1       honda civic   Black         95000      4  18000                 4
3            bmw x5    Blue         80000      4  45000                 4

In [80]:
cars_sales["odometer(km)"]=cars_sales["odometer(km)"].apply(lambda x: x/1.6)
cars_sales

               name   color  odometer(km)  doors  price  number of wheels
0    toyota corolla   White     46875.000      4  15000                 4
1       honda civic   Black     37109.375      4  18000                 4
2      ford mustang     Red     23437.500      2  35000                 4
3            bmw x5    Blue     31250.000      4  45000                 4
4  mercedes c-class  Silver     27343.750      4  40000                 4
5   hyundai elantra    Grey     42968.750      4  14000                 4
6      kia sportage   White     35156.250      4  22000                 4
7     nissan altima   Black     39062.500      4  16000                 4
8   volkswagen golf    Blue     33203.125      4  19000                 4
9           audi a4     Red     29296.875      4  38000                 4